const shops = [
  {
    id: 1,
    shop_name: "Style Street",
    verified: true,
    distance: "850 m away",
    location: "Brigade Road, Bengaluru",
    description: "Trendy fashion for every occasion. Discover your style with us.",
    categories: ["Men", "Women", "Bags & Accessories"],
    rating: 4.7,
    reviews: 215,
    trusted_seller: true,
    fast_delivery: true,
    shop_image: "https://images.unsplash.com/photo-1567521464027-f127ff144326?w=400&h=300&fit=crop"
  },
  {
    id: 2,
    shop_name: "Toy Town",
    verified: true,
    distance: "950 m away",
    location: "1st Main Road, Indiranagar, Bengaluru",
    description: "Fun, safe & educational toys for kids of all ages. Play more, learn more!",
    categories: ["Soft Toys", "Educational Toys", "Action Figures"],
    rating: 4.8,
    reviews: 362,
    trusted_seller: true,
    fast_delivery: true,
    shop_image: "https://images.unsplash.com/photo-1565225557007-c7b5a3d11900?w=400&h=300&fit=crop"
  },
  {
    id: 3,
    shop_name: "Fresh Mart",
    verified: true,
    distance: "500 m away",
    location: "MG Road, Bengaluru",
    description: "Fresh groceries and daily essentials at affordable prices.",
    categories: ["Groceries", "Vegetables", "Dairy"],
    rating: 4.6,
    reviews: 189,
    trusted_seller: true,
    fast_delivery: false,
    shop_image: "https://images.unsplash.com/photo-1516321318423-f06f70a504f0?w=400&h=300&fit=crop"
  },
  {
    id: 4,
    shop_name: "Mobile Hub",
    verified: true,
    distance: "1.2 km away",
    location: "Commercial Street, Bengaluru",
    description: "Latest smartphones, accessories, and gadgets available here.",
    categories: ["Mobiles", "Accessories", "Smart Gadgets"],
    rating: 4.5,
    reviews: 420,
    trusted_seller: true,
    fast_delivery: true,
    shop_image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=300&fit=crop"
  },
  {
    id: 5,
    shop_name: "Home Harmony",
    verified: true,
    distance: "700 m away",
    location: "Whitefield, Bengaluru",
    description: "Complete home decor solutions and furniture for modern living.",
    categories: ["Furniture", "Decor", "Lighting"],
    rating: 4.6,
    reviews: 278,
    trusted_seller: true,
    fast_delivery: true,
    shop_image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop"
  },
  {
    id: 6,
    shop_name: "Beauty Bliss",
    verified: true,
    distance: "1.1 km away",
    location: "Indiranagar, Bengaluru",
    description: "Premium beauty and cosmetics products from top brands worldwide.",
    categories: ["Makeup", "Skincare", "Hair Care"],
    rating: 4.9,
    reviews: 445,
    trusted_seller: true,
    fast_delivery: true,
    shop_image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop"
  },
  {
    id: 7,
    shop_name: "Sports Zone",
    verified: true,
    distance: "1.5 km away",
    location: "Marathahalli, Bengaluru",
    description: "Complete sports equipment and activewear for fitness enthusiasts.",
    categories: ["Sportswear", "Equipment", "Footwear"],
    rating: 4.4,
    reviews: 156,
    trusted_seller: true,
    fast_delivery: true,
    shop_image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop"
  },
  {
    id: 8,
    shop_name: "Tech Paradise",
    verified: true,
    distance: "800 m away",
    location: "Koramangala, Bengaluru",
    description: "Premium electronics and latest tech gadgets at best prices.",
    categories: ["Laptops", "Tablets", "Cameras"],
    rating: 4.7,
    reviews: 523,
    trusted_seller: true,
    fast_delivery: true,
    shop_image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=300&fit=crop"
  }
];

export default shops;
